version: '3'
services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=mylife
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password123
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"